language:
  elixir

env:
  global:
    - MIX_ENV=test

jobs:
  include:

    - stage: test
      otp_release: 20.2
      elixir: 1.6.4
      script:
        # Run the tests
        - mix compile
        - mix do credo --strict, format --check-formatted --dry-run
        - mix coveralls.travis
